# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gaggioli Sposi
author: Gaggioli Sposi
email: info@gaggiolisposi.it
description: Abiti da Sposa, Abiti da Sposo, Proposte per la Cerimonia # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.gaggiolisposi.it # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/logo-gaggioli-sposi-centrato.jpg"
twitter_username: jekyllrb
github_username: piotr17
phonenumber: +393791507510
watext: "gaggiolisposi.it"
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-menus
  - jekyll-seo-tag
lang: it_IT
sass:
  sass_dir: _sass
  style: compressed
include: ["_redirects"]

profile: true
collections:
  sposo:
    output: true
  sposa:
    output: true
  accessori:
    output: true
  outlet-sposa:
    output: true
  outlet-sposo:
    output: true
  outlet-cerimonia:
    output: true
  cerimonia:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
