new_page_extension: md
auto_deploy: false
admin_path: ""
? webhook_url
sections:
  - type: directory
    path: _sposo
    label: Sposo
    create: all
    match: "**/*"
  - type: directory
    path: _sposa
    label: Sposa
    create: all
    match: "**/*"
  - type: directory
    path: _accessori
    label: Accessori
    create: all
    match: "**/*"
  - type: directory
    path: _outlet-sposa
    label: Outlet Sposa
    create: all
    match: "**/*"
  - type: directory
    path: _outlet-sposo
    label: Outlet Sposo
    create: all
    match: "**/*"
  - type: directory
    path: _cerimonia
    label: Cerimonia
    create: all
    match: "**/*"
  - type: directory
    path: _outlet-cerimonia
    label: Outlet Cerimonia
    create: all
    match: "**/*"
  - type: jekyll-pages
    label: Pages
    create: all
  - type: jekyll-posts
    label: Posts
    create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ""
use_front_matter_path: false
file_template: ":filename:"
